spring:
  application:
    name: demo
  datasource:
    url: "jdbc:postgresql://localhost5432/ecommerce"
    username: postgres
    password: test
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostegreSQLDialect
  showSql: true
  hibernate:
    ddlAuto: validate
server:
  port: 8080